

#include "CloseCanHolder.h"

CloseCanHolder::CloseCanHolder() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::canHolder);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void CloseCanHolder::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void CloseCanHolder::Execute() {
	Robot::canHolder->Close();
}

// Make this return true when this Command no longer needs to run execute()
bool CloseCanHolder::IsFinished() {
	return Robot::canHolder->canClosedLimitSwitch->Get();
}

// Called once after isFinished returns true
void CloseCanHolder::End() {
	Robot::canHolder->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CloseCanHolder::Interrupted() {
	End();
}
