// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

const float length = 0;
const double Kp = -0.5;

#include "DriveForward750.h"
#include <iostream>

DriveForward750::DriveForward750() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void DriveForward750::Initialize() {
	Robot::driveTrain->driveEncoder->Reset();
	Robot::driveTrain->driveGyro->Reset();
}

// Called repeatedly when this Command is scheduled to run
void DriveForward750::Execute() {
	Robot::driveTrain->AutoDrive(-0.5, Robot::driveTrain->driveGyro->GetAngle() * Kp);
}

// Make this return true when this Command no longer needs to run execute()
bool DriveForward750::IsFinished() {
	return (Robot::driveTrain->driveEncoder->Get() >= 740) && (Robot::driveTrain->driveEncoder->Get() <= 760);
}

// Called once after isFinished returns true
void DriveForward750::End() {
	Robot::driveTrain->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveForward750::Interrupted() {
	End();
}
